export const REMOTE_ANALYSIS_MAX_MESSAGES = 10;
export const REMOTE_ANALYSIS_MAX_TEXT_CODE_POINTS = 280;
export const REMOTE_INTERPRETATION_MAX_CODE_POINTS = 150;
export const REMOTE_ANALYSIS_MAX_RESPONSE_BYTES = 40 * 1024;
export const REMOTE_DRAFT_MAX_RESPONSE_BYTES = 32 * 1024;
